# ETH3D Low-Resolution, Multi-View Delivery Area Dataset

# Dataset Details
# dataset_dir: "/Users/saulll./Desktop/Independent Study/datasets"
# output_dir: "/Users/saulll./Desktop/Independent Study/outputs"
dataset_dir: "/gpfs/data/bkimia/Datasets/"
output_dir: "/gpfs/data/bkimia/cchien3/Edge_Based_Visual_Odometry/outputs"
sequence_name: "ETH3D/stereo/delivery_area_rig_stereo_pairs_gt/delivery_area"
dataset_type: "ETH3D"

# Stereo Intrinsic Parameters
left_camera:
  resolution: [942, 489]
  intrinsics: [541.764, 541.764, 553.869, 232.396]
  distortion_coefficients: [0, 0, 0, 0]

right_camera:
  resolution: [942, 489]
  intrinsics: [541.764, 541.764, 553.869, 232.396]
  distortion_coefficients: [0, 0, 0, 0]

# Stereo Extrinsic Parameters
stereo:
  #Left Image to Right Image
  R21:
  - [1.000000000000000, 0.000000000000000, 0.000000000000000]
  - [0.000000000000000, 1.000000000000000, 0.000000000000000]
  - [0.000000000000000, 0.000000000000000, 1.000000000000000]

  T21: [-0.059891300000001, 0.000000000000001, 0.000000000000001]
  
  F21: 
  - [0.000000000000000,   0.000000000000000,  0.000000000000000]
  - [0.000000000000000,  0.000000000000000,   0.000110548689097]
  - [0.000000000000000,  -0.000110548689097,  0.000000000000000]

  #Right Image to Left Image
  R12:
  - [1.000000000000000,  0.000000000000000,  0.000000000000000]
  - [0.000000000000000,   1.000000000000000,  0.000000000000000]
  - [0.000000000000000,   0.000000000000000,   1.000000000000000]

  T12: [0.059891300000001, -0.000000000000001, -0.000000000000001]
  
  F12: 
  - [0.000000000000000,  0.000000000000000,   0.000000000000000]
  - [0.000000000000000,  0.000000000000000,  -0.000110548689097]
  - [0.000000000000000,   0.000110548689097,  0.000000000000000]

  focal_length: 541.764
  baseline: 0.0599101